databases:
  quests: # Database name automatically corresponds to the section name.
    # Available services: ["mysql", "postgresql", "mariadb"] (ignored upper/lower chars).
    service: "mysql"
    host: "localhost"
    user: "root"
    pass: ""
    port: 3306
    # Relative path to the database file. Used if your service corresponds to "sqlite". Otherwise, it will be ignored.
    sqlite_path: "databases/quests.db"